server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.at.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: mysql
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-provider-dept8001 #eurekaURL修改服务名
    prefer-ip-address: true #访问路径可以显示IP地址

info:
 app.name: atguigu-microservicecloud
 company.name: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$

