CREATE TABLE source_info (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  name varchar(50) DEFAULT NULL COMMENT '数据源名称',
  remark varchar(255) DEFAULT NULL COMMENT '备注',
  source_type int(11) DEFAULT NULL COMMENT '数据源类型',
  source_key varchar(50) DEFAULT NULL COMMENT '数据源唯一标示',
  url varchar(1024) DEFAULT NULL COMMENT '连接地址',
  host varchar(100) DEFAULT NULL COMMENT 'IP或主机名',
  port int(11) DEFAULT NULL COMMENT '端口',
  database_name varchar(50) DEFAULT NULL COMMENT '库名',
  catalog_name varchar(50) DEFAULT NULL COMMENT 'catalog',
  schema_name varchar(50) DEFAULT NULL COMMENT 'schema',
  username varchar(50) DEFAULT NULL COMMENT '用户名',
  password varchar(50) DEFAULT NULL COMMENT '密码',
  credential varchar(1024) DEFAULT NULL COMMENT '密码凭证在默认文件服务器中的Key',
  credential_url varchar(1024) DEFAULT NULL COMMENT '密码凭证在数据源文件服务器中的URL',
  driver_file varchar(1024) DEFAULT NULL COMMENT '驱动文件在默认文件服务器中的Key',
  driver_file_url varchar(1024) DEFAULT NULL COMMENT '驱动文件在数据源文件服务器中的URL',
  driver_class varchar(100) DEFAULT NULL COMMENT '驱动类',
  initial_size int(11) DEFAULT NULL COMMENT '初始化连接池大小',
  max_active int(11) DEFAULT NULL COMMENT '最大活动连接',
  min_idle int(11) DEFAULT NULL COMMENT '最小空闲连接',
  max_wait int(11) DEFAULT NULL COMMENT '最大等待时长（毫秒）',
  validation_query varchar(200) DEFAULT NULL COMMENT '校验连接是否有效的SQL',
  custom_pro text COMMENT '自定义属性，JSON格式',
  custom_url_pro text COMMENT 'JSON格式，自定义文件属性在数据源文件服务器中的URL保存在这里',
  is_inset int(2) DEFAULT NULL COMMENT '是否内置数据源',
  is_enabled int(2) DEFAULT NULL COMMENT '是否启用',
  public_source int(2) DEFAULT NULL COMMENT '是否公开的数据源',
  app_ids varchar(1024) DEFAULT NULL COMMENT '未公开数据源，允许使用该数据源的应用ID，逗号分隔',
  create_user int(11) DEFAULT NULL COMMENT '创建人',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_user int(11) DEFAULT NULL COMMENT '修改人',
  update_time datetime DEFAULT NULL COMMENT '修改时间',
  delete_user int(11) DEFAULT NULL COMMENT '删除人',
  delete_time datetime DEFAULT NULL COMMENT '删除时间',
  data_state varchar(50) DEFAULT NULL COMMENT '数据的逻辑状态（1：有效，非1：无效）',
  PRIMARY KEY (id),
  UNIQUE KEY source_info_1 (name, data_state)
) AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COMMENT='数据源信息';

